
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// `prisma generate` only needs this to load the schema — it never opens a
// connection — so a placeholder keeps the build working on platforms (like
// Netlify) that don't set DATABASE_URL, since the runtime client connects
// via the libSQL adapter (see lib/prisma.ts) instead.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: process.env.DATABASE_URL ?? "file:./prisma/dev.db",
  },
});
